# Generated by Django 5.2 on 2025-04-24 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_trim'),
    ]

    operations = [
        migrations.AddField(
            model_name='trim',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trim_models', to='customadmin.carcompany'),
            preserve_default=False,
        ),
    ]
