# Generated by Django 5.2 on 2025-04-24 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_servicecategory_serviceitem_applicableservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='min_price',
        ),
        migrations.CreateModel(
            name='TrimServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trim_prices', to='customadmin.serviceitem')),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='customadmin.trim')),
            ],
            options={
                'unique_together': {('trim', 'service_item')},
            },
        ),
        migrations.DeleteModel(
            name='ApplicableService',
        ),
    ]
