# Generated by Django 5.2 on 2025-04-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcompany',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='customadmin.country'),
            preserve_default=False,
        ),
    ]
