# Generated by Django 5.2 on 2025-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0008_carcompany_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='symbole',
            field=models.CharField(choices=[('$', '$'), ('€', '€'), ('£', '£'), ('¥', '¥'), ('¥元', '¥ / 元'), ('₹', '₹'), ('A$', 'A$'), ('C$', 'C$'), ('CHF', 'CHF'), ('₽', '₽'), ('₩', '₩'), ('R$', 'R$'), ('ZAR', 'R'), ('Mex$', 'Mex$'), ('NZ$', 'NZ$'), ('S$', 'S$'), ('HK$', 'HK$'), ('SEK', 'kr (SEK)'), ('NOK', 'kr (NOK)'), ('DKK', 'kr (DKK)'), ('₺', '₺'), ('฿', '฿'), ('RM', 'RM'), ('Rp', 'Rp'), ('₱', '₱'), ('₪', '₪'), ('SR', 'SR'), ('E£', 'E£'), ('₫', '₫'), ('₦', '₦')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
