# Generated by Django 5.2 on 2025-06-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0011_tyre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tyre",
            name="car_model",
        ),
        migrations.RemoveField(
            model_name="tyre",
            name="size",
        ),
        migrations.AddField(
            model_name="tyre",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tyre_models",
                to="customadmin.carcompany",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tyre",
            name="model",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tyre",
                to="customadmin.carmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tyre",
            name="trim",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tyre_trim",
                to="customadmin.trim",
            ),
            preserve_default=False,
        ),
    ]
