from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='home'),
    path('carlist/', views.car_list, name='car_list'),
    path('add-carlist/', views.add_carlist, name='add_carlist'),
    path('update-carlist/<int:id>/', views.add_carlist, name='update_carlist'),
    path('delete-carlist/<int:id>/', views.delete_carlist, name='delete_carlist'),
    path('carmodel/', views.car_model_list, name='car_model_list'),
    path('add-carmodel/', views.add_carmodel, name='add_carmodel'),
    path('update-carmodel/<int:id>/', views.add_carmodel, name='update_carmodel'),
    path('delete-carmodel/<int:id>/', views.delete_carmodel, name='delete_carmodel'),
    path('trim/', views.trim, name='trim'),
    path('add-trim/', views.add_trim, name='add_trim'),
    path('update-trim/<int:id>/', views.add_trim, name='update_trim'),
    path('delete-trim/<int:id>/', views.delete_trim, name='delete_trim'),
    path('get-model/', views.get_model, name='get_model'),
    path('get-car/', views.get_car, name='get_car'),
    path('get-trim/', views.get_trim, name='get_trim'),
    path('get_trim_service/', views.get_trim_service, name='get_trim_service'),
    path('servicecategory/', views.servicecategory, name='servicecategory'),
    path('add-servicecategory/', views.add_servicecategory, name='add_servicecategory'),
    path('update-servicecategory/<int:id>/', views.add_servicecategory, name='update_servicecategory'),
    path('delete-servicecategory/<int:id>/', views.delete_servicecategory, name='delete_servicecategory'),
    
    path('serviceitem/', views.serviceitem, name='serviceitem'),
    path('add-serviceitem/', views.add_serviceitem, name='add_serviceitem'),
    path('update-serviceitem/<int:id>/', views.add_serviceitem, name='update_serviceitem'),
    path('delete-serviceitem/<int:id>/', views.delete_serviceitem, name='delete_serviceitem'),
    path('country/', views.country_list, name='country_list'),
    path('country_create/', views.country_create, name='country_create'),
    path('country_update/<int:pk>/', views.country_update, name='country_update'),
    path('country_delete/<int:pk>/', views.country_delete, name='country_delete'),

    path('tyre/', views.tyre, name='tyre'),
    path('tyre_create/', views.tyre_create, name='tyre_create'),
    path('tyre_update/<int:pk>/', views.tyre_update, name='tyre_update'),
    path('tyre_delete/<int:pk>/', views.tyre_delete, name='tyre_delete'),
]